---

- name: copy Zabbix agent to remote servers
  copy:
          src: zabbixagent.tar
          dest: /home/ansible/
          remote_src: no
          owner: root
          group: root
          mode: '0644'

- name: Podman Load Zabbix Agent
  shell:
          cmd: podman load -i /home/ansible/zabbixagent.tar

- name: Run Zabbix Agent command
  shell:
          cmd: podman run --name zabbix-agent --ip {{ zbx_ip }} -e ZBX_HOSTNAME={{ hostName }} -e ZBX_SERVER_HOST=1.2.3.45 --network=podman -p 10050:10050 -d artifact.saleh.miri.docker.io/zabbix/zabbix-agent:latest
