---
- name: add zabbix repo for site1
  blockinfile:
          path: /etc/yum.repos.d/site1.repo
          block: |
                  [zabbix]
                  name=zabbix
                  baseurl=http://repo-site1:80/repository/zabbix
                  enabled=1
                  gpgcheck=0

  when: ansible_facts['default_ipv4']['gateway'] == "1.2.1.1" or ansible_facts['default_ipv4']['gateway'] == "1.3.1.1"
  
#########
- name: add zabbix repo for site2
  blockinfile:
          path: /etc/yum.repos.d/site2.repo
          block: |
                  [zabbix]
                  name=zabbix
                  baseurl=http://repo-site2:80/repository/zabbix
                  enabled=1
                  gpgcheck=0

  when: ansible_facts['default_ipv4']['gateway'] == "1.4.1.1" or ansible_facts['default_ipv4']['gateway'] == "1.5.1.1"
