---

- name: Generate bootable RHEL ISO from {{ file_path }}
  shell: >
          mkisofs
          -o {{ iso_path }}/{{ item.hostName }}.iso
          -b isolinux/isolinux.bin
          -J
          -R
          -l
          -c isolinux/boot.cat
          -no-emul-boot
          -boot-load-size 4
          -boot-info-table
          -eltorito-alt-boot
          -e images/efiboot.img
          -no-emul-boot
          -graft-points
          -joliet-long
          "{{ file_path }}"/{{ item.hostName }}/
  with_items:
          - "{{ hosts }}"
