---
- name: Install and configure Prometheus Blackbox Exporter
  hosts: all
  become: true

  tasks:
    - name: Copy blackbox exporter tarball to target
      copy:
        src: "files/{{ blackbox_archive }}"
        dest: "/tmp/{{ blackbox_archive }}"
        mode: '0644'

    - name: Extract blackbox exporter archive
      unarchive:
        src: "/tmp/{{ blackbox_archive }}"
        dest: "/tmp/"
        remote_src: true

    - name: Move binary to /usr/local/bin
      copy:
        src: "/tmp/{{ blackbox_dir }}/blackbox_exporter"
        dest: "{{ blackbox_bin_path }}"
        mode: '0755'
        remote_src: true

    - name: Create configuration directory
      file:
        path: "{{ blackbox_config_dir }}"
        state: directory
        mode: '0755'

    - name: Create blackbox exporter config file
      copy:
        dest: "{{ blackbox_config_file }}"
        content: |
          modules:
            tcp_connect_example:
              prober: tcp
              timeout: 5s
        mode: '0644'

    - name: Create systemd service file
      copy:
        dest: "{{ blackbox_service_path }}"
        content: |
          [Unit]
          Description=Prometheus Blackbox Exporter
          After=network.target

          [Service]
          User=root
          Type=simple
          ExecStart={{ blackbox_bin_path }} --config.file={{ blackbox_config_file }}
          Restart=always

          [Install]
          WantedBy=multi-user.target
        mode: '0644'

    - name: Reload systemd daemon
      systemd:
        daemon_reload: true

    - name: Enable and start blackbox_exporter service
      systemd:
        name: blackbox_exporter
        enabled: true
        state: started

