---
# this playbook use host_vars file to run
- name: Using HPE iLO to {{ ilo_state }} target physical servers
  hpilo_boot:
          host: "{{ ilo_ip }}"
          login: "{{ ilo_user }}"
          password: "{{ ilo_pass }}"
          state: "{{ ilo_state }}"
          media: cdrom
          image: http://saleh.miri/rhel-8.6-ks-grub.iso
  delegate_to: localhost
