---

- hosts: server
  gather_facts: yes
  tasks:
          - name: add offline repo
            include_role:
                    name: offline-repo
            ignore_errors: yes

          - name: install & configure zabbix
            include_role:
                    name: zabbix
            ignore_errors: yes
