---

file_path: /home/deploy/baremetal


### Create LVM for 300GB Disk, modify as you want
#Number's value are MegaByte (MB)
#osDisk: 
#pv01_size: 79874
#pv02_size: 204290
#root_size: 51200
#home_size: 20480
#var_size: 204200

### Create LVM for 600GB Disk, modify as you want
#Number's value are MegaByte (MB)
#osDisk: 
pv01_size: 80000
pv02_size: 490500
root_size: 51200
home_size: 20480
var_size: 490490
