---
- name: update repo cache for the new repo
  command: yum repolist

- name: Install a zabbix-agent2 from the repository
  yum:
          name: "zabbix-agent2.x86_64"
          state: present

- name: Enable zabbix service
  service:
          name:  zabbix-agent2.service
          enabled: yes

- name: zabbix config file site1
  blockinfile:
          path: /etc/zabbix/zabbix_agent2.conf
          block: |
                  Server=zabbix-site1.saleh.miri
                  ServerActive=zabbix-site1.saleh.miri
  when: ansible_facts['default_ipv4']['gateway'] == "1.2.1.1" or ansible_facts['default_ipv4']['gateway'] == "1.3.1.1"
#########
- name: zabbix config file site2
  blockinfile:
          path: /etc/zabbix/zabbix_agent2.conf
          block: |
                  Server=zabbix-site2.saleh.miri
                  ServerActive=zabbix-site2.saleh.miri
  when: ansible_facts['default_ipv4']['gateway'] == "1.4.1.1" or ansible_facts['default_ipv4']['gateway'] == "1.5.1.1"
#########
- name: Retrieve hostname
  set_fact:
          hostname: "{{ ansible_hostname }}"

- name: Append hostname to file
  lineinfile:
          path: /etc/zabbix/zabbix_agent2.conf
          line: "Hostname={{ hostname }}"
          state: present
  notify: Restart zabbix
