---

- name: set Timezone To city
  timezone:
          name: Asia/City

- name: delete chrony old config
  shell:
          cmd: sed -i '/iburst/d' /etc/chrony.conf

- name: modify chrony file for US Clusters
  shell:
          cmd: sed -i '3 i \server {{ ntp_us[0] }} iburst \nserver {{ ntp_us[1] }} iburst \n ' /etc/chrony.conf
  when: ansible_facts['default_ipv4']['gateway'] == "1.23.7.254"

- name: modify chrony file for UK Clusters
  shell:
          cmd: sed -i '3 i \server {{ ntp_uk[0] }} iburst \nserver {{ ntp_uk[1] }} iburst \n ' /etc/chrony.conf
  when: ansible_facts['default_ipv4']['gateway'] == "142.1.7.254"

- name: modify chrony file for UAE Clusters
  shell:
          cmd: sed -i '3 i \server {{ ntp_uae[0] }} iburst \nserver {{ ntp_uae[1] }} iburst \n ' /etc/chrony.conf
  when: ansible_facts['default_ipv4']['gateway'] == "1.14.9.254"

- name: restart chrony service
  service:
          name: chronyd
          state: restarted
          enabled: yes

